apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patoughi-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/patoughi/platform-tms-driver-api.git
    targetRevision: HEAD
    path: dev  # Path to your Kubernetes manifests
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: patoughi-driver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
