name: Build And Push to Docker Hub

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'production'

env:
  DOCKER_HUB_REPOSITORY: abbass69/driver

permissions:
  contents: read

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - List files
        run: ls -la

      - name: Check for Dockerfile
        run: |
          if [ -f "Dockerfile" ]; then
            echo "✅ Dockerfile found"
            cat Dockerfile | head -10
          else
            echo "❌ Dockerfile not found!"
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building image: $DOCKER_HUB_REPOSITORY"
          echo "Tags: latest and $IMAGE_TAG"

          # Build with progress output
          docker build --progress=plain -t $DOCKER_HUB_REPOSITORY:latest -t $DOCKER_HUB_REPOSITORY:$IMAGE_TAG . 2>&1 | tee build.log

          # Check if build succeeded
          if [ $? -eq 0 ]; then
            echo "✅ Build successful"

            # List images to verify
            docker images | grep "$DOCKER_HUB_REPOSITORY"

            # Push images
            echo "Pushing images..."
            docker push $DOCKER_HUB_REPOSITORY:latest
            docker push $DOCKER_HUB_REPOSITORY:$IMAGE_TAG

            echo "image=$DOCKER_HUB_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          else
            echo "❌ Build failed"
            cat build.log
            exit 1
          fi

      - name: Verify push
        run: |
          echo "Verifying images were pushed..."
          docker pull $DOCKER_HUB_REPOSITORY:latest
          docker images
